---
title: "Research"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Publications  

<b>Leap, B.</b> & [Young, J](http://fs2.american.edu/jyoung/www/). (2021, May 26). [Radicalization and deradicalization](https://urldefense.com/v3/__https://oxfordre.com/internationalstudies/view/10.1093/acrefore/9780190846626.001.0001/acrefore-9780190846626-e-601__;!!IaT_gp1N!mm2VQflygQPIlEuJb-aN9vyz_mytFe3wQy-sYck9texJ2jDp3Rfp9Di68lr_3j776A$.). In *Oxford Research Encyclopedia of International Studies*. Oxford University Press. doi: https://doi.org/10.1093/acrefore/9780190846626.013.601.

## Articles  
<u>Leap, B. </u> "A Machine Learning Approach to Predicting Behavioral Radicalization among the Far Right." Working Manuscript. 

<u>Leap, B.</u> "Using Computational Text Analysis to Analyze Trends in the Radicalization Literature." Working Manuscript.  

## Research Assistant
"Mapping the Far Right," with [Joseph K. Young](http://fs2.american.edu/jyoung/www/).

## Conferences 
"A Computational Approach to Combating the Pitfalls of Terrorism Data". *Midwest Political Science Association Annual Meeting*, Chicago, IL. Upcoming.

"Death & Math; or Why We Like Terrorism... Research," with Joe Young. *Admitted Doctoral Student Day*, School of Public Affairs, American University, Washington, DC. March 2021.

"Terrorizing Democracy? A Bayesian Analysis of Terrorism's Effects on Democratic Institutions." *Tri-School Doctoral Research Conference*, Washington, DC. March 2021.  

"Ticking Time Bombs: The Effects of Indiscriminate Violence on Civil War Outcomes." *Midwest Political Science Association Annual Meeting*, Chicago, IL. April 2019.  

"Ticking Time Bombs: The Effects of Indiscriminate Violence on Civil War Outcomes." *Life-of-the-Scholar Multidisciplinary Conference*, Boiling Springs, NC. March 2019.  
